### ISSUE TITLE
Работа с промежутками

### ISSUE THREAD

**Issue by DaemoncheG** [ndra/infuso#5]
По старому проекту появилась потребность сделать выборку из бд с помощью промежутков, но я не знаю как это организовывается в infuso через встроенные запросы.

У нас есть промежуток А
A < 20 AND A > 10

Промежутки в БД попадающие под значение A
B < 25 AND B > 15
C < 15 AND C > 5
D < 17 AND D > 12
Z < 25 AND D > 5

Промежутки в БД не попадающие под значение A
E < 30 AND E > 25
G < 9 AND G > 5

Как сделать аналог mysql запроса, для поиска промежутков с которыми пересекается A

``` mysql
SELECT * FROM `range` WHERE `min`>10 AND `min`<20 OR `max`>10 AND `max`<20 OR `min`<10 AND `max`>20
```

**Comment by ndra** [comment]
Превед, самый простой способ реализовать это написать $collection->where("`min`>10 AND `min`<20 OR `max`>10 AND `max`<20")

**Comment by petrgrishin** [comment]
Вопрос не по теме `infuso`.

А секцию `where` можно разложить так:

``` php
$collection
    ->where('`min` > 10 AND `min` < 20')
    ->orr()
    ->where('`max` > 10 AND `max` < 20');
```

**Comment by DaemoncheG** [comment]
глупый гитхабедитор всё съел
т.е. mysql запрос

``` mysql
SELECT * FROM `range` WHERE `min`>10 AND `min`<20 OR `max`>10 AND `max`<20 OR `min`<10 AND `max`>20
```

аналог в инфузо

``` php
$collection->where('`min`>10 AND `min`<20 OR `max`>10 AND `max`<20 OR `min`<10 AND `max`'>20)
```

или правильнее так как Пётр пишет?

``` php
$collection
    ->where('`min` > 10 AND `min` < 20')
    ->orr()
    ->where('`max` > 10 AND `max` < 20')
    ->orr()
    ->where('`min` < 10 AND `max` > 20')
;
```

**Comment by ndra** [comment]
Да можно и так и так. Разбивать на несколько частей смысла нет, только если для наглядности.

**Comment by petrgrishin** [comment]
@ndra: это улучшает понимание кода, в этом есть смысл.

А вообще лучше строить цепочки такого вида:

``` php
$criteria = new Criteria();
$criteria
    ->addCondition('min > :lowerLimit AND min < :upperLimit', Criteria::OR)
    ->addCondition('max > :lowerLimit AND max < :upperLimit', Criteria::OR)
    ->params(array(
        ':lowerLimit' => 10,
        ':upperLimit' => 20,
    ));
$model->find($criteria);
```

**Comment by DaemoncheG** [comment]
выглядит красиво, тока мне уже не понятно.
